* Encoding: UTF-8.
WEIGHT BY f.

FREQUENCIES VARIABLES=x
  /STATISTICS=MINIMUM MEAN
  /ORDER=ANALYSIS.

COMPUTE px=PDF.POISSON(x,1.15).
EXECUTE.

COMPUTE exp_f=PDF.POISSON(x,1.15) *  6904.
EXECUTE.

COMPUTE rounded_exp_f=RND(PDF.POISSON(x,1.15) *  6904).
EXECUTE.
